package fund_management_system;


import javax.swing.*;
import java.awt.*;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
package fund_management_system;
import java.awt.BorderLayout;
import javax.swing.*;
import javax.swing.JLabel;
import javax.swing.JPanel;
/*
package fund_management_system;
import javax.swing.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Aryan
 */
/*
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
/*
    public NewJFrame() {
        initComponents();
         addasset addAssetFrame = new addasset();
              jTabbedPane1.addTab("tab2", addAssetFrame.getContentPane());
        
        // Add the content pane of addasset to the jPanel3 (second tab)
        jPanel3.add(addAssetFrame.getContentPane());
         jTabbedPane1.addChangeListener(e -> {
            // Check if the second tab is selected
            if (jTabbedPane1.getSelectedIndex() == 1) {
                // Refresh or repaint the addasset panel
                addAssetFrame.getContentPane().validate();
                addAssetFrame.getContentPane().repaint();
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
/*
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setText("transactional history");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(630, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
/*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
/*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
*/
        /*
public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
    initComponents();

    // Create an instance of the addasset class
    addasset addAssetFrame = new addasset();
    // Add addasset frame to the second tab
    jTabbedPane1.addTab("tab2", addAssetFrame.getContentPane());

    // Create an instance of the portfolio class
    portfolio portfolioFrame = new portfolio();
    // Add portfolio frame to the third tab
    jTabbedPane1.addTab("tab3", portfolioFrame.getContentPane());
    
    // Create an instance of the login class
    Loginnew loginFrame = new Loginnew();
    // Add login frame to the first tab
    jTabbedPane1.addTab("tab1", loginFrame.getContentPane());

    // Create an instance of the signup class
    Signupnew signupFrame = new Signupnew();
    // Add signup frame to the fourth tab
    jTabbedPane1.addTab("tab4", signupFrame.getContentPane());
    
    // Adding JLabels to each tab
    jTabbedPane1.addChangeListener(e -> {
        // Check if the second tab is selected
        if (jTabbedPane1.getSelectedIndex() == 1) {
            // Refresh or repaint the addasset panel
            addAssetFrame.getContentPane().validate();
            addAssetFrame.getContentPane().repaint();
        }
        // Check if the first tab is selected
        else if (jTabbedPane1.getSelectedIndex() == 0) {
            // Refresh or repaint the login panel
            loginFrame.getContentPane().validate();
            loginFrame.getContentPane().repaint();
        }
        // Check if the fourth tab is selected
        else if (jTabbedPane1.getSelectedIndex() == 3) {
            // Refresh or repaint the signup panel
            signupFrame.getContentPane().validate();
            signupFrame.getContentPane().repaint();
        }
    });

    // Create a button for dashboard
     JButton dashboardButton = new JButton("Dashboard");
    // Add an ActionListener to handle button clicks
    dashboardButton.addActionListener(ex -> {
        // Switch to the desired tab (e.g., second tab)
        jTabbedPane1.setSelectedIndex(1); // Change 1 to the index of the desired tab
    });
    // Add the button to the JFrame
    getContentPane().add(dashboardButton, BorderLayout.NORTH);
    setVisible(true);// Add the button to the desired location in your layout
} // Add the button to the desired location in your layout


    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
}
*/


public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
        initComponents();

        // Create an instance of each class corresponding to the tabs
        addasset addAssetFrame = new addasset();
        portfolio portfolioFrame = new portfolio();
        Loginnew loginFrame = new Loginnew();
        Signupnew signupFrame = new Signupnew();

        // Add each class frame to its corresponding tab
        jTabbedPane1.addTab("Add Asset", addAssetFrame.getContentPane());
        jTabbedPane1.addTab("Portfolio", portfolioFrame.getContentPane());
        jTabbedPane1.addTab("Login", loginFrame.getContentPane());
        jTabbedPane1.addTab("Signup", signupFrame.getContentPane());

        // Add a change listener to the tabbed pane
        jTabbedPane1.addChangeListener(e -> {
            // Check which tab is selected
            switch (jTabbedPane1.getSelectedIndex()) {
                case 0: // Add Asset tab
                    System.out.println("Add Asset tab selected");
                    break;
                case 1: // Portfolio tab
                    System.out.println("Portfolio tab selected");
                    break;
                case 2: // Login tab
                    System.out.println("Login tab selected");
                    break;
                case 3: // Signup tab
                    System.out.println("Signup tab selected");
                    break;
                default:
                    break;
            }
        });

        // Create a button for dashboard
        JButton dashboardButton = new JButton("Dashboard");
        // Add an ActionListener to handle button clicks
        dashboardButton.addActionListener(ex -> {
            // Switch to the desired tab (e.g., Portfolio tab)
            jTabbedPane1.setSelectedIndex(1); // Change 1 to the index of the desired tab
        });
        // Add the button to the JFrame
        getContentPane().add(dashboardButton, BorderLayout.NORTH);
        setVisible(true);
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
}

